# Generated by Django 3.0.8 on 2020-08-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.PositiveIntegerField()),
                ('organisation', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
            ],
        ),
    ]
