# Generated by Django 3.0.8 on 2020-07-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.PositiveIntegerField()),
                ('CO', models.PositiveIntegerField()),
                ('CU', models.PositiveIntegerField()),
                ('even', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.PositiveIntegerField()),
                ('organisation', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_forecast', models.PositiveIntegerField()),
                ('LB', models.PositiveIntegerField()),
                ('UB', models.PositiveIntegerField()),
                ('target_fill_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='newsvendor.question')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='newsvendor.user')),
            ],
        ),
    ]
