# Generated by Django 3.0.8 on 2020-07-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='qid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='uid',
            field=models.PositiveIntegerField(),
        ),
    ]
