# Generated by Django 3.0.8 on 2020-08-04 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvendor', '0002_auto_20200727_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data',
            field=models.CharField(default=100, max_length=15, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
    ]
