# Generated by Django 3.0.8 on 2020-08-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicnv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField()),
                ('roundid', models.PositiveIntegerField()),
                ('point_forecast', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rounds',
            fields=[
                ('roundid', models.AutoField(primary_key=True, serialize=False)),
                ('actualdemand', models.PositiveIntegerField()),
            ],
        ),
    ]
