# Generated by Django 3.0.8 on 2020-08-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicnv', '0002_answer_rounds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='answer',
            new_name='answers',
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
    ]
